// Generated by gencpp from file dji_sdk_web_groundstation/WebWaypointReceiveGoal.msg
// DO NOT EDIT!


#ifndef DJI_SDK_WEB_GROUNDSTATION_MESSAGE_WEBWAYPOINTRECEIVEGOAL_H
#define DJI_SDK_WEB_GROUNDSTATION_MESSAGE_WEBWAYPOINTRECEIVEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dji_sdk/WaypointList.h>

namespace dji_sdk_web_groundstation
{
template <class ContainerAllocator>
struct WebWaypointReceiveGoal_
{
  typedef WebWaypointReceiveGoal_<ContainerAllocator> Type;

  WebWaypointReceiveGoal_()
    : waypoint_list()
    , tid(0)  {
    }
  WebWaypointReceiveGoal_(const ContainerAllocator& _alloc)
    : waypoint_list(_alloc)
    , tid(0)  {
  (void)_alloc;
    }



   typedef  ::dji_sdk::WaypointList_<ContainerAllocator>  _waypoint_list_type;
  _waypoint_list_type waypoint_list;

   typedef uint64_t _tid_type;
  _tid_type tid;




  typedef boost::shared_ptr< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct WebWaypointReceiveGoal_

typedef ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<std::allocator<void> > WebWaypointReceiveGoal;

typedef boost::shared_ptr< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal > WebWaypointReceiveGoalPtr;
typedef boost::shared_ptr< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal const> WebWaypointReceiveGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dji_sdk_web_groundstation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'dji_sdk': ['/home/bobby/fyp/catkin_ws/src/Onboard-SDK-ROS/dji_sdk/msg', '/home/bobby/fyp/catkin_ws/devel/share/dji_sdk/msg'], 'dji_sdk_web_groundstation': ['/home/bobby/fyp/catkin_ws/src/Onboard-SDK-ROS/dji_sdk_web_groundstation/msg', '/home/bobby/fyp/catkin_ws/devel/share/dji_sdk_web_groundstation/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ec8abdbbe8f44dcf91e84ea5b8df4d8";
  }

  static const char* value(const ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ec8abdbbe8f44dcULL;
  static const uint64_t static_value2 = 0xf91e84ea5b8df4d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_sdk_web_groundstation/WebWaypointReceiveGoal";
  }

  static const char* value(const ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
dji_sdk/WaypointList waypoint_list\n\
#task id\n\
uint64 tid\n\
\n\
================================================================================\n\
MSG: dji_sdk/WaypointList\n\
Waypoint[] waypoint_list\n\
\n\
================================================================================\n\
MSG: dji_sdk/Waypoint\n\
#latitude is in degree\n\
float64 latitude\n\
#longitude is in degree\n\
float64 longitude\n\
float32 altitude\n\
#heading is in [-180,180]\n\
int16 heading \n\
#stay time is in second\n\
uint16 staytime\n\
";
  }

  static const char* value(const ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoint_list);
      stream.next(m.tid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WebWaypointReceiveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_sdk_web_groundstation::WebWaypointReceiveGoal_<ContainerAllocator>& v)
  {
    s << indent << "waypoint_list: ";
    s << std::endl;
    Printer< ::dji_sdk::WaypointList_<ContainerAllocator> >::stream(s, indent + "  ", v.waypoint_list);
    s << indent << "tid: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.tid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_SDK_WEB_GROUNDSTATION_MESSAGE_WEBWAYPOINTRECEIVEGOAL_H
