// Generated by gencpp from file dji_pid/move_target.msg
// DO NOT EDIT!


#ifndef DJI_PID_MESSAGE_MOVE_TARGET_H
#define DJI_PID_MESSAGE_MOVE_TARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dji_pid
{
template <class ContainerAllocator>
struct move_target_
{
  typedef move_target_<ContainerAllocator> Type;

  move_target_()
    : header()
    , stick_state(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  move_target_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , stick_state(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _stick_state_type;
  _stick_state_type stick_state;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;




  typedef boost::shared_ptr< ::dji_pid::move_target_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_pid::move_target_<ContainerAllocator> const> ConstPtr;

}; // struct move_target_

typedef ::dji_pid::move_target_<std::allocator<void> > move_target;

typedef boost::shared_ptr< ::dji_pid::move_target > move_targetPtr;
typedef boost::shared_ptr< ::dji_pid::move_target const> move_targetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_pid::move_target_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_pid::move_target_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dji_pid

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'dji_pid': ['/home/bobby/fyp/catkin_ws/src/pid_controller/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dji_pid::move_target_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_pid::move_target_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_pid::move_target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_pid::move_target_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_pid::move_target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_pid::move_target_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_pid::move_target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c07253b6b2b88818f5453c7b18d44a3";
  }

  static const char* value(const ::dji_pid::move_target_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c07253b6b2b8881ULL;
  static const uint64_t static_value2 = 0x8f5453c7b18d44a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_pid::move_target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_pid/move_target";
  }

  static const char* value(const ::dji_pid::move_target_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_pid::move_target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 stick_state\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::dji_pid::move_target_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_pid::move_target_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.stick_state);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct move_target_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_pid::move_target_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_pid::move_target_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "stick_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stick_state);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_PID_MESSAGE_MOVE_TARGET_H
