// Generated by gencpp from file bluefox2/SetExposeSrv.msg
// DO NOT EDIT!


#ifndef BLUEFOX2_MESSAGE_SETEXPOSESRV_H
#define BLUEFOX2_MESSAGE_SETEXPOSESRV_H

#include <ros/service_traits.h>


#include <bluefox2/SetExposeSrvRequest.h>
#include <bluefox2/SetExposeSrvResponse.h>


namespace bluefox2
{

struct SetExposeSrv
{

typedef SetExposeSrvRequest Request;
typedef SetExposeSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetExposeSrv
} // namespace bluefox2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bluefox2::SetExposeSrv > {
  static const char* value()
  {
    return "75265de6308041cab01352a6d59078cb";
  }

  static const char* value(const ::bluefox2::SetExposeSrv&) { return value(); }
};

template<>
struct DataType< ::bluefox2::SetExposeSrv > {
  static const char* value()
  {
    return "bluefox2/SetExposeSrv";
  }

  static const char* value(const ::bluefox2::SetExposeSrv&) { return value(); }
};


// service_traits::MD5Sum< ::bluefox2::SetExposeSrvRequest> should match 
// service_traits::MD5Sum< ::bluefox2::SetExposeSrv > 
template<>
struct MD5Sum< ::bluefox2::SetExposeSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bluefox2::SetExposeSrv >::value();
  }
  static const char* value(const ::bluefox2::SetExposeSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bluefox2::SetExposeSrvRequest> should match 
// service_traits::DataType< ::bluefox2::SetExposeSrv > 
template<>
struct DataType< ::bluefox2::SetExposeSrvRequest>
{
  static const char* value()
  {
    return DataType< ::bluefox2::SetExposeSrv >::value();
  }
  static const char* value(const ::bluefox2::SetExposeSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bluefox2::SetExposeSrvResponse> should match 
// service_traits::MD5Sum< ::bluefox2::SetExposeSrv > 
template<>
struct MD5Sum< ::bluefox2::SetExposeSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bluefox2::SetExposeSrv >::value();
  }
  static const char* value(const ::bluefox2::SetExposeSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bluefox2::SetExposeSrvResponse> should match 
// service_traits::DataType< ::bluefox2::SetExposeSrv > 
template<>
struct DataType< ::bluefox2::SetExposeSrvResponse>
{
  static const char* value()
  {
    return DataType< ::bluefox2::SetExposeSrv >::value();
  }
  static const char* value(const ::bluefox2::SetExposeSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BLUEFOX2_MESSAGE_SETEXPOSESRV_H
