// Generated by gencpp from file bluefox2/SetExposeSrvResponse.msg
// DO NOT EDIT!


#ifndef BLUEFOX2_MESSAGE_SETEXPOSESRVRESPONSE_H
#define BLUEFOX2_MESSAGE_SETEXPOSESRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bluefox2
{
template <class ContainerAllocator>
struct SetExposeSrvResponse_
{
  typedef SetExposeSrvResponse_<ContainerAllocator> Type;

  SetExposeSrvResponse_()
    : status(false)  {
    }
  SetExposeSrvResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetExposeSrvResponse_

typedef ::bluefox2::SetExposeSrvResponse_<std::allocator<void> > SetExposeSrvResponse;

typedef boost::shared_ptr< ::bluefox2::SetExposeSrvResponse > SetExposeSrvResponsePtr;
typedef boost::shared_ptr< ::bluefox2::SetExposeSrvResponse const> SetExposeSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bluefox2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::bluefox2::SetExposeSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluefox2/SetExposeSrvResponse";
  }

  static const char* value(const ::bluefox2::SetExposeSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n\
\n\
";
  }

  static const char* value(const ::bluefox2::SetExposeSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetExposeSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluefox2::SetExposeSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluefox2::SetExposeSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUEFOX2_MESSAGE_SETEXPOSESRVRESPONSE_H
