// Generated by gencpp from file n3_sdk/AttitudeControl.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_ATTITUDECONTROL_H
#define N3_SDK_MESSAGE_ATTITUDECONTROL_H

#include <ros/service_traits.h>


#include <n3_sdk/AttitudeControlRequest.h>
#include <n3_sdk/AttitudeControlResponse.h>


namespace n3_sdk
{

struct AttitudeControl
{

typedef AttitudeControlRequest Request;
typedef AttitudeControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AttitudeControl
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::AttitudeControl > {
  static const char* value()
  {
    return "29c0571c7f764a69752f1f1d3dac2ca2";
  }

  static const char* value(const ::n3_sdk::AttitudeControl&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::AttitudeControl > {
  static const char* value()
  {
    return "n3_sdk/AttitudeControl";
  }

  static const char* value(const ::n3_sdk::AttitudeControl&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::AttitudeControlRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::AttitudeControl > 
template<>
struct MD5Sum< ::n3_sdk::AttitudeControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::AttitudeControl >::value();
  }
  static const char* value(const ::n3_sdk::AttitudeControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::AttitudeControlRequest> should match 
// service_traits::DataType< ::n3_sdk::AttitudeControl > 
template<>
struct DataType< ::n3_sdk::AttitudeControlRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::AttitudeControl >::value();
  }
  static const char* value(const ::n3_sdk::AttitudeControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::AttitudeControlResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::AttitudeControl > 
template<>
struct MD5Sum< ::n3_sdk::AttitudeControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::AttitudeControl >::value();
  }
  static const char* value(const ::n3_sdk::AttitudeControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::AttitudeControlResponse> should match 
// service_traits::DataType< ::n3_sdk::AttitudeControl > 
template<>
struct DataType< ::n3_sdk::AttitudeControlResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::AttitudeControl >::value();
  }
  static const char* value(const ::n3_sdk::AttitudeControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_ATTITUDECONTROL_H
