// Generated by gencpp from file n3_sdk/CameraActionControl.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_CAMERAACTIONCONTROL_H
#define N3_SDK_MESSAGE_CAMERAACTIONCONTROL_H

#include <ros/service_traits.h>


#include <n3_sdk/CameraActionControlRequest.h>
#include <n3_sdk/CameraActionControlResponse.h>


namespace n3_sdk
{

struct CameraActionControl
{

typedef CameraActionControlRequest Request;
typedef CameraActionControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraActionControl
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::CameraActionControl > {
  static const char* value()
  {
    return "77629488af3edd3adaa94bf250d692c6";
  }

  static const char* value(const ::n3_sdk::CameraActionControl&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::CameraActionControl > {
  static const char* value()
  {
    return "n3_sdk/CameraActionControl";
  }

  static const char* value(const ::n3_sdk::CameraActionControl&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::CameraActionControlRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::CameraActionControl > 
template<>
struct MD5Sum< ::n3_sdk::CameraActionControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::CameraActionControl >::value();
  }
  static const char* value(const ::n3_sdk::CameraActionControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::CameraActionControlRequest> should match 
// service_traits::DataType< ::n3_sdk::CameraActionControl > 
template<>
struct DataType< ::n3_sdk::CameraActionControlRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::CameraActionControl >::value();
  }
  static const char* value(const ::n3_sdk::CameraActionControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::CameraActionControlResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::CameraActionControl > 
template<>
struct MD5Sum< ::n3_sdk::CameraActionControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::CameraActionControl >::value();
  }
  static const char* value(const ::n3_sdk::CameraActionControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::CameraActionControlResponse> should match 
// service_traits::DataType< ::n3_sdk::CameraActionControl > 
template<>
struct DataType< ::n3_sdk::CameraActionControlResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::CameraActionControl >::value();
  }
  static const char* value(const ::n3_sdk::CameraActionControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_CAMERAACTIONCONTROL_H
