// Generated by gencpp from file n3_sdk/DroneArmControl.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_DRONEARMCONTROL_H
#define N3_SDK_MESSAGE_DRONEARMCONTROL_H

#include <ros/service_traits.h>


#include <n3_sdk/DroneArmControlRequest.h>
#include <n3_sdk/DroneArmControlResponse.h>


namespace n3_sdk
{

struct DroneArmControl
{

typedef DroneArmControlRequest Request;
typedef DroneArmControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DroneArmControl
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::DroneArmControl > {
  static const char* value()
  {
    return "dd0555f68f747c630a22ca214d8ef45c";
  }

  static const char* value(const ::n3_sdk::DroneArmControl&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::DroneArmControl > {
  static const char* value()
  {
    return "n3_sdk/DroneArmControl";
  }

  static const char* value(const ::n3_sdk::DroneArmControl&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::DroneArmControlRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::DroneArmControl > 
template<>
struct MD5Sum< ::n3_sdk::DroneArmControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::DroneArmControl >::value();
  }
  static const char* value(const ::n3_sdk::DroneArmControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::DroneArmControlRequest> should match 
// service_traits::DataType< ::n3_sdk::DroneArmControl > 
template<>
struct DataType< ::n3_sdk::DroneArmControlRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::DroneArmControl >::value();
  }
  static const char* value(const ::n3_sdk::DroneArmControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::DroneArmControlResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::DroneArmControl > 
template<>
struct MD5Sum< ::n3_sdk::DroneArmControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::DroneArmControl >::value();
  }
  static const char* value(const ::n3_sdk::DroneArmControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::DroneArmControlResponse> should match 
// service_traits::DataType< ::n3_sdk::DroneArmControl > 
template<>
struct DataType< ::n3_sdk::DroneArmControlResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::DroneArmControl >::value();
  }
  static const char* value(const ::n3_sdk::DroneArmControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_DRONEARMCONTROL_H
