// Generated by gencpp from file n3_sdk/DroneArmControlRequest.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_DRONEARMCONTROLREQUEST_H
#define N3_SDK_MESSAGE_DRONEARMCONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace n3_sdk
{
template <class ContainerAllocator>
struct DroneArmControlRequest_
{
  typedef DroneArmControlRequest_<ContainerAllocator> Type;

  DroneArmControlRequest_()
    : arm(0)  {
    }
  DroneArmControlRequest_(const ContainerAllocator& _alloc)
    : arm(0)  {
  (void)_alloc;
    }



   typedef uint8_t _arm_type;
  _arm_type arm;




  typedef boost::shared_ptr< ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DroneArmControlRequest_

typedef ::n3_sdk::DroneArmControlRequest_<std::allocator<void> > DroneArmControlRequest;

typedef boost::shared_ptr< ::n3_sdk::DroneArmControlRequest > DroneArmControlRequestPtr;
typedef boost::shared_ptr< ::n3_sdk::DroneArmControlRequest const> DroneArmControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace n3_sdk

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'n3_sdk': ['/home/ubuntu/fyp/catkin_ws/src/ugv/n3_sdk/msg', '/home/ubuntu/fyp/catkin_ws/devel/share/n3_sdk/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e21c483c8d5b2db4fad7ea96e4e9cd5f";
  }

  static const char* value(const ::n3_sdk::DroneArmControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe21c483c8d5b2db4ULL;
  static const uint64_t static_value2 = 0xfad7ea96e4e9cd5fULL;
};

template<class ContainerAllocator>
struct DataType< ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "n3_sdk/DroneArmControlRequest";
  }

  static const char* value(const ::n3_sdk::DroneArmControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 arm\n\
";
  }

  static const char* value(const ::n3_sdk::DroneArmControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DroneArmControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::n3_sdk::DroneArmControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::n3_sdk::DroneArmControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "arm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.arm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // N3_SDK_MESSAGE_DRONEARMCONTROLREQUEST_H
