// Generated by gencpp from file n3_sdk/DroneTaskControl.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_DRONETASKCONTROL_H
#define N3_SDK_MESSAGE_DRONETASKCONTROL_H

#include <ros/service_traits.h>


#include <n3_sdk/DroneTaskControlRequest.h>
#include <n3_sdk/DroneTaskControlResponse.h>


namespace n3_sdk
{

struct DroneTaskControl
{

typedef DroneTaskControlRequest Request;
typedef DroneTaskControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DroneTaskControl
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::DroneTaskControl > {
  static const char* value()
  {
    return "0a416eed4867a07da37526125142e150";
  }

  static const char* value(const ::n3_sdk::DroneTaskControl&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::DroneTaskControl > {
  static const char* value()
  {
    return "n3_sdk/DroneTaskControl";
  }

  static const char* value(const ::n3_sdk::DroneTaskControl&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::DroneTaskControlRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::DroneTaskControl > 
template<>
struct MD5Sum< ::n3_sdk::DroneTaskControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::DroneTaskControl >::value();
  }
  static const char* value(const ::n3_sdk::DroneTaskControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::DroneTaskControlRequest> should match 
// service_traits::DataType< ::n3_sdk::DroneTaskControl > 
template<>
struct DataType< ::n3_sdk::DroneTaskControlRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::DroneTaskControl >::value();
  }
  static const char* value(const ::n3_sdk::DroneTaskControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::DroneTaskControlResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::DroneTaskControl > 
template<>
struct MD5Sum< ::n3_sdk::DroneTaskControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::DroneTaskControl >::value();
  }
  static const char* value(const ::n3_sdk::DroneTaskControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::DroneTaskControlResponse> should match 
// service_traits::DataType< ::n3_sdk::DroneTaskControl > 
template<>
struct DataType< ::n3_sdk::DroneTaskControlResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::DroneTaskControl >::value();
  }
  static const char* value(const ::n3_sdk::DroneTaskControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_DRONETASKCONTROL_H
