// Generated by gencpp from file n3_sdk/GimbalAngleControl.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_GIMBALANGLECONTROL_H
#define N3_SDK_MESSAGE_GIMBALANGLECONTROL_H

#include <ros/service_traits.h>


#include <n3_sdk/GimbalAngleControlRequest.h>
#include <n3_sdk/GimbalAngleControlResponse.h>


namespace n3_sdk
{

struct GimbalAngleControl
{

typedef GimbalAngleControlRequest Request;
typedef GimbalAngleControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GimbalAngleControl
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::GimbalAngleControl > {
  static const char* value()
  {
    return "355893b815576f75c0061dddd133c146";
  }

  static const char* value(const ::n3_sdk::GimbalAngleControl&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::GimbalAngleControl > {
  static const char* value()
  {
    return "n3_sdk/GimbalAngleControl";
  }

  static const char* value(const ::n3_sdk::GimbalAngleControl&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::GimbalAngleControlRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::GimbalAngleControl > 
template<>
struct MD5Sum< ::n3_sdk::GimbalAngleControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::GimbalAngleControl >::value();
  }
  static const char* value(const ::n3_sdk::GimbalAngleControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::GimbalAngleControlRequest> should match 
// service_traits::DataType< ::n3_sdk::GimbalAngleControl > 
template<>
struct DataType< ::n3_sdk::GimbalAngleControlRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::GimbalAngleControl >::value();
  }
  static const char* value(const ::n3_sdk::GimbalAngleControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::GimbalAngleControlResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::GimbalAngleControl > 
template<>
struct MD5Sum< ::n3_sdk::GimbalAngleControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::GimbalAngleControl >::value();
  }
  static const char* value(const ::n3_sdk::GimbalAngleControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::GimbalAngleControlResponse> should match 
// service_traits::DataType< ::n3_sdk::GimbalAngleControl > 
template<>
struct DataType< ::n3_sdk::GimbalAngleControlResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::GimbalAngleControl >::value();
  }
  static const char* value(const ::n3_sdk::GimbalAngleControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_GIMBALANGLECONTROL_H
