// Generated by gencpp from file n3_sdk/GlobalPositionControl.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_GLOBALPOSITIONCONTROL_H
#define N3_SDK_MESSAGE_GLOBALPOSITIONCONTROL_H

#include <ros/service_traits.h>


#include <n3_sdk/GlobalPositionControlRequest.h>
#include <n3_sdk/GlobalPositionControlResponse.h>


namespace n3_sdk
{

struct GlobalPositionControl
{

typedef GlobalPositionControlRequest Request;
typedef GlobalPositionControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GlobalPositionControl
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::GlobalPositionControl > {
  static const char* value()
  {
    return "760463c3d8356eaf13428439b7b2ac10";
  }

  static const char* value(const ::n3_sdk::GlobalPositionControl&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::GlobalPositionControl > {
  static const char* value()
  {
    return "n3_sdk/GlobalPositionControl";
  }

  static const char* value(const ::n3_sdk::GlobalPositionControl&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::GlobalPositionControlRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::GlobalPositionControl > 
template<>
struct MD5Sum< ::n3_sdk::GlobalPositionControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::GlobalPositionControl >::value();
  }
  static const char* value(const ::n3_sdk::GlobalPositionControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::GlobalPositionControlRequest> should match 
// service_traits::DataType< ::n3_sdk::GlobalPositionControl > 
template<>
struct DataType< ::n3_sdk::GlobalPositionControlRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::GlobalPositionControl >::value();
  }
  static const char* value(const ::n3_sdk::GlobalPositionControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::GlobalPositionControlResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::GlobalPositionControl > 
template<>
struct MD5Sum< ::n3_sdk::GlobalPositionControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::GlobalPositionControl >::value();
  }
  static const char* value(const ::n3_sdk::GlobalPositionControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::GlobalPositionControlResponse> should match 
// service_traits::DataType< ::n3_sdk::GlobalPositionControl > 
template<>
struct DataType< ::n3_sdk::GlobalPositionControlResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::GlobalPositionControl >::value();
  }
  static const char* value(const ::n3_sdk::GlobalPositionControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_GLOBALPOSITIONCONTROL_H
