// Generated by gencpp from file n3_sdk/MessageFrequencyControl.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MESSAGEFREQUENCYCONTROL_H
#define N3_SDK_MESSAGE_MESSAGEFREQUENCYCONTROL_H

#include <ros/service_traits.h>


#include <n3_sdk/MessageFrequencyControlRequest.h>
#include <n3_sdk/MessageFrequencyControlResponse.h>


namespace n3_sdk
{

struct MessageFrequencyControl
{

typedef MessageFrequencyControlRequest Request;
typedef MessageFrequencyControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MessageFrequencyControl
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::MessageFrequencyControl > {
  static const char* value()
  {
    return "631e88e1468cdc8d59e5bd64d8267053";
  }

  static const char* value(const ::n3_sdk::MessageFrequencyControl&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::MessageFrequencyControl > {
  static const char* value()
  {
    return "n3_sdk/MessageFrequencyControl";
  }

  static const char* value(const ::n3_sdk::MessageFrequencyControl&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::MessageFrequencyControlRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::MessageFrequencyControl > 
template<>
struct MD5Sum< ::n3_sdk::MessageFrequencyControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MessageFrequencyControl >::value();
  }
  static const char* value(const ::n3_sdk::MessageFrequencyControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MessageFrequencyControlRequest> should match 
// service_traits::DataType< ::n3_sdk::MessageFrequencyControl > 
template<>
struct DataType< ::n3_sdk::MessageFrequencyControlRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MessageFrequencyControl >::value();
  }
  static const char* value(const ::n3_sdk::MessageFrequencyControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::MessageFrequencyControlResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::MessageFrequencyControl > 
template<>
struct MD5Sum< ::n3_sdk::MessageFrequencyControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MessageFrequencyControl >::value();
  }
  static const char* value(const ::n3_sdk::MessageFrequencyControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MessageFrequencyControlResponse> should match 
// service_traits::DataType< ::n3_sdk::MessageFrequencyControl > 
template<>
struct DataType< ::n3_sdk::MessageFrequencyControlResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MessageFrequencyControl >::value();
  }
  static const char* value(const ::n3_sdk::MessageFrequencyControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_MESSAGEFREQUENCYCONTROL_H
