// Generated by gencpp from file n3_sdk/MissionWaypointAction.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MISSIONWAYPOINTACTION_H
#define N3_SDK_MESSAGE_MISSIONWAYPOINTACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace n3_sdk
{
template <class ContainerAllocator>
struct MissionWaypointAction_
{
  typedef MissionWaypointAction_<ContainerAllocator> Type;

  MissionWaypointAction_()
    : action_repeat(0)
    , command_list()
    , command_parameter()  {
      command_list.assign(0);

      command_parameter.assign(0);
  }
  MissionWaypointAction_(const ContainerAllocator& _alloc)
    : action_repeat(0)
    , command_list()
    , command_parameter()  {
  (void)_alloc;
      command_list.assign(0);

      command_parameter.assign(0);
  }



   typedef uint8_t _action_repeat_type;
  _action_repeat_type action_repeat;

   typedef boost::array<uint8_t, 15>  _command_list_type;
  _command_list_type command_list;

   typedef boost::array<int16_t, 15>  _command_parameter_type;
  _command_parameter_type command_parameter;




  typedef boost::shared_ptr< ::n3_sdk::MissionWaypointAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::n3_sdk::MissionWaypointAction_<ContainerAllocator> const> ConstPtr;

}; // struct MissionWaypointAction_

typedef ::n3_sdk::MissionWaypointAction_<std::allocator<void> > MissionWaypointAction;

typedef boost::shared_ptr< ::n3_sdk::MissionWaypointAction > MissionWaypointActionPtr;
typedef boost::shared_ptr< ::n3_sdk::MissionWaypointAction const> MissionWaypointActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::n3_sdk::MissionWaypointAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::n3_sdk::MissionWaypointAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace n3_sdk

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'n3_sdk': ['/home/ubuntu/fyp/catkin_ws/src/ugv/n3_sdk/msg', '/home/ubuntu/fyp/catkin_ws/devel/share/n3_sdk/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::n3_sdk::MissionWaypointAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::n3_sdk::MissionWaypointAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n3_sdk::MissionWaypointAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n3_sdk::MissionWaypointAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n3_sdk::MissionWaypointAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n3_sdk::MissionWaypointAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::n3_sdk::MissionWaypointAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc8a44f81cb941d4399400060a0a73d6";
  }

  static const char* value(const ::n3_sdk::MissionWaypointAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc8a44f81cb941d4ULL;
  static const uint64_t static_value2 = 0x399400060a0a73d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::n3_sdk::MissionWaypointAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "n3_sdk/MissionWaypointAction";
  }

  static const char* value(const ::n3_sdk::MissionWaypointAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::n3_sdk::MissionWaypointAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 action_repeat\n\
uint8[15] command_list\n\
int16[15] command_parameter\n\
";
  }

  static const char* value(const ::n3_sdk::MissionWaypointAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::n3_sdk::MissionWaypointAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_repeat);
      stream.next(m.command_list);
      stream.next(m.command_parameter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionWaypointAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::n3_sdk::MissionWaypointAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::n3_sdk::MissionWaypointAction_<ContainerAllocator>& v)
  {
    s << indent << "action_repeat: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action_repeat);
    s << indent << "command_list[]" << std::endl;
    for (size_t i = 0; i < v.command_list.size(); ++i)
    {
      s << indent << "  command_list[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.command_list[i]);
    }
    s << indent << "command_parameter[]" << std::endl;
    for (size_t i = 0; i < v.command_parameter.size(); ++i)
    {
      s << indent << "  command_parameter[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.command_parameter[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // N3_SDK_MESSAGE_MISSIONWAYPOINTACTION_H
