// Generated by gencpp from file n3_sdk/MissionFmUploadRequest.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MISSIONFMUPLOADREQUEST_H
#define N3_SDK_MESSAGE_MISSIONFMUPLOADREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <n3_sdk/MissionFollowmeTask.h>

namespace n3_sdk
{
template <class ContainerAllocator>
struct MissionFmUploadRequest_
{
  typedef MissionFmUploadRequest_<ContainerAllocator> Type;

  MissionFmUploadRequest_()
    : followme_task()  {
    }
  MissionFmUploadRequest_(const ContainerAllocator& _alloc)
    : followme_task(_alloc)  {
  (void)_alloc;
    }



   typedef  ::n3_sdk::MissionFollowmeTask_<ContainerAllocator>  _followme_task_type;
  _followme_task_type followme_task;




  typedef boost::shared_ptr< ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MissionFmUploadRequest_

typedef ::n3_sdk::MissionFmUploadRequest_<std::allocator<void> > MissionFmUploadRequest;

typedef boost::shared_ptr< ::n3_sdk::MissionFmUploadRequest > MissionFmUploadRequestPtr;
typedef boost::shared_ptr< ::n3_sdk::MissionFmUploadRequest const> MissionFmUploadRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace n3_sdk

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'n3_sdk': ['/home/ubuntu/fyp/catkin_ws/src/ugv/n3_sdk/msg', '/home/ubuntu/fyp/catkin_ws/devel/share/n3_sdk/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9cd25f0a53a1d10e6538dd9fb391a7e8";
  }

  static const char* value(const ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9cd25f0a53a1d10eULL;
  static const uint64_t static_value2 = 0x6538dd9fb391a7e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "n3_sdk/MissionFmUploadRequest";
  }

  static const char* value(const ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MissionFollowmeTask followme_task\n\
\n\
================================================================================\n\
MSG: n3_sdk/MissionFollowmeTask\n\
uint8 mode\n\
uint8 yaw_mode\n\
float64 initial_latitude\n\
float64 initial_longitude\n\
uint16 initial_altitude\n\
uint8 sensitivity\n\
";
  }

  static const char* value(const ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.followme_task);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionFmUploadRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::n3_sdk::MissionFmUploadRequest_<ContainerAllocator>& v)
  {
    s << indent << "followme_task: ";
    s << std::endl;
    Printer< ::n3_sdk::MissionFollowmeTask_<ContainerAllocator> >::stream(s, indent + "  ", v.followme_task);
  }
};

} // namespace message_operations
} // namespace ros

#endif // N3_SDK_MESSAGE_MISSIONFMUPLOADREQUEST_H
