// Generated by gencpp from file n3_sdk/MissionWpGetSpeed.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MISSIONWPGETSPEED_H
#define N3_SDK_MESSAGE_MISSIONWPGETSPEED_H

#include <ros/service_traits.h>


#include <n3_sdk/MissionWpGetSpeedRequest.h>
#include <n3_sdk/MissionWpGetSpeedResponse.h>


namespace n3_sdk
{

struct MissionWpGetSpeed
{

typedef MissionWpGetSpeedRequest Request;
typedef MissionWpGetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionWpGetSpeed
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::MissionWpGetSpeed > {
  static const char* value()
  {
    return "ca65bba734a79b4a6707341d829f4d5c";
  }

  static const char* value(const ::n3_sdk::MissionWpGetSpeed&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::MissionWpGetSpeed > {
  static const char* value()
  {
    return "n3_sdk/MissionWpGetSpeed";
  }

  static const char* value(const ::n3_sdk::MissionWpGetSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::MissionWpGetSpeedRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionWpGetSpeed > 
template<>
struct MD5Sum< ::n3_sdk::MissionWpGetSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionWpGetSpeed >::value();
  }
  static const char* value(const ::n3_sdk::MissionWpGetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionWpGetSpeedRequest> should match 
// service_traits::DataType< ::n3_sdk::MissionWpGetSpeed > 
template<>
struct DataType< ::n3_sdk::MissionWpGetSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionWpGetSpeed >::value();
  }
  static const char* value(const ::n3_sdk::MissionWpGetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::MissionWpGetSpeedResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionWpGetSpeed > 
template<>
struct MD5Sum< ::n3_sdk::MissionWpGetSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionWpGetSpeed >::value();
  }
  static const char* value(const ::n3_sdk::MissionWpGetSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionWpGetSpeedResponse> should match 
// service_traits::DataType< ::n3_sdk::MissionWpGetSpeed > 
template<>
struct DataType< ::n3_sdk::MissionWpGetSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionWpGetSpeed >::value();
  }
  static const char* value(const ::n3_sdk::MissionWpGetSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_MISSIONWPGETSPEED_H
