// Generated by gencpp from file n3_sdk/MissionHpSetRadius.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MISSIONHPSETRADIUS_H
#define N3_SDK_MESSAGE_MISSIONHPSETRADIUS_H

#include <ros/service_traits.h>


#include <n3_sdk/MissionHpSetRadiusRequest.h>
#include <n3_sdk/MissionHpSetRadiusResponse.h>


namespace n3_sdk
{

struct MissionHpSetRadius
{

typedef MissionHpSetRadiusRequest Request;
typedef MissionHpSetRadiusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionHpSetRadius
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::MissionHpSetRadius > {
  static const char* value()
  {
    return "44e997bb8d1a50ef179a59895af1c426";
  }

  static const char* value(const ::n3_sdk::MissionHpSetRadius&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::MissionHpSetRadius > {
  static const char* value()
  {
    return "n3_sdk/MissionHpSetRadius";
  }

  static const char* value(const ::n3_sdk::MissionHpSetRadius&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::MissionHpSetRadiusRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionHpSetRadius > 
template<>
struct MD5Sum< ::n3_sdk::MissionHpSetRadiusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionHpSetRadius >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpSetRadiusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionHpSetRadiusRequest> should match 
// service_traits::DataType< ::n3_sdk::MissionHpSetRadius > 
template<>
struct DataType< ::n3_sdk::MissionHpSetRadiusRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionHpSetRadius >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpSetRadiusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::MissionHpSetRadiusResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionHpSetRadius > 
template<>
struct MD5Sum< ::n3_sdk::MissionHpSetRadiusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionHpSetRadius >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpSetRadiusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionHpSetRadiusResponse> should match 
// service_traits::DataType< ::n3_sdk::MissionHpSetRadius > 
template<>
struct DataType< ::n3_sdk::MissionHpSetRadiusResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionHpSetRadius >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpSetRadiusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_MISSIONHPSETRADIUS_H
