// Generated by gencpp from file n3_sdk/MissionHpResetYaw.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MISSIONHPRESETYAW_H
#define N3_SDK_MESSAGE_MISSIONHPRESETYAW_H

#include <ros/service_traits.h>


#include <n3_sdk/MissionHpResetYawRequest.h>
#include <n3_sdk/MissionHpResetYawResponse.h>


namespace n3_sdk
{

struct MissionHpResetYaw
{

typedef MissionHpResetYawRequest Request;
typedef MissionHpResetYawResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionHpResetYaw
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::MissionHpResetYaw > {
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::n3_sdk::MissionHpResetYaw&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::MissionHpResetYaw > {
  static const char* value()
  {
    return "n3_sdk/MissionHpResetYaw";
  }

  static const char* value(const ::n3_sdk::MissionHpResetYaw&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::MissionHpResetYawRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionHpResetYaw > 
template<>
struct MD5Sum< ::n3_sdk::MissionHpResetYawRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionHpResetYaw >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpResetYawRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionHpResetYawRequest> should match 
// service_traits::DataType< ::n3_sdk::MissionHpResetYaw > 
template<>
struct DataType< ::n3_sdk::MissionHpResetYawRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionHpResetYaw >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpResetYawRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::MissionHpResetYawResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionHpResetYaw > 
template<>
struct MD5Sum< ::n3_sdk::MissionHpResetYawResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionHpResetYaw >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpResetYawResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionHpResetYawResponse> should match 
// service_traits::DataType< ::n3_sdk::MissionHpResetYaw > 
template<>
struct DataType< ::n3_sdk::MissionHpResetYawResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionHpResetYaw >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpResetYawResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_MISSIONHPRESETYAW_H
