// Generated by gencpp from file n3_sdk/MissionWpDownload.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MISSIONWPDOWNLOAD_H
#define N3_SDK_MESSAGE_MISSIONWPDOWNLOAD_H

#include <ros/service_traits.h>


#include <n3_sdk/MissionWpDownloadRequest.h>
#include <n3_sdk/MissionWpDownloadResponse.h>


namespace n3_sdk
{

struct MissionWpDownload
{

typedef MissionWpDownloadRequest Request;
typedef MissionWpDownloadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionWpDownload
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::MissionWpDownload > {
  static const char* value()
  {
    return "7c965e82a72d204e1e6d1e75389efb89";
  }

  static const char* value(const ::n3_sdk::MissionWpDownload&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::MissionWpDownload > {
  static const char* value()
  {
    return "n3_sdk/MissionWpDownload";
  }

  static const char* value(const ::n3_sdk::MissionWpDownload&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::MissionWpDownloadRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionWpDownload > 
template<>
struct MD5Sum< ::n3_sdk::MissionWpDownloadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionWpDownload >::value();
  }
  static const char* value(const ::n3_sdk::MissionWpDownloadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionWpDownloadRequest> should match 
// service_traits::DataType< ::n3_sdk::MissionWpDownload > 
template<>
struct DataType< ::n3_sdk::MissionWpDownloadRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionWpDownload >::value();
  }
  static const char* value(const ::n3_sdk::MissionWpDownloadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::MissionWpDownloadResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionWpDownload > 
template<>
struct MD5Sum< ::n3_sdk::MissionWpDownloadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionWpDownload >::value();
  }
  static const char* value(const ::n3_sdk::MissionWpDownloadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionWpDownloadResponse> should match 
// service_traits::DataType< ::n3_sdk::MissionWpDownload > 
template<>
struct DataType< ::n3_sdk::MissionWpDownloadResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionWpDownload >::value();
  }
  static const char* value(const ::n3_sdk::MissionWpDownloadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_MISSIONWPDOWNLOAD_H
