// Generated by gencpp from file n3_sdk/MissionHpSetSpeed.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MISSIONHPSETSPEED_H
#define N3_SDK_MESSAGE_MISSIONHPSETSPEED_H

#include <ros/service_traits.h>


#include <n3_sdk/MissionHpSetSpeedRequest.h>
#include <n3_sdk/MissionHpSetSpeedResponse.h>


namespace n3_sdk
{

struct MissionHpSetSpeed
{

typedef MissionHpSetSpeedRequest Request;
typedef MissionHpSetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionHpSetSpeed
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::MissionHpSetSpeed > {
  static const char* value()
  {
    return "da0df5b8181232e1f4ba7f7d4faba414";
  }

  static const char* value(const ::n3_sdk::MissionHpSetSpeed&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::MissionHpSetSpeed > {
  static const char* value()
  {
    return "n3_sdk/MissionHpSetSpeed";
  }

  static const char* value(const ::n3_sdk::MissionHpSetSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::MissionHpSetSpeedRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionHpSetSpeed > 
template<>
struct MD5Sum< ::n3_sdk::MissionHpSetSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionHpSetSpeed >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpSetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionHpSetSpeedRequest> should match 
// service_traits::DataType< ::n3_sdk::MissionHpSetSpeed > 
template<>
struct DataType< ::n3_sdk::MissionHpSetSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionHpSetSpeed >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpSetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::MissionHpSetSpeedResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionHpSetSpeed > 
template<>
struct MD5Sum< ::n3_sdk::MissionHpSetSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionHpSetSpeed >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpSetSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionHpSetSpeedResponse> should match 
// service_traits::DataType< ::n3_sdk::MissionHpSetSpeed > 
template<>
struct DataType< ::n3_sdk::MissionHpSetSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionHpSetSpeed >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpSetSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_MISSIONHPSETSPEED_H
