// Generated by gencpp from file n3_sdk/MissionHpUpload.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MISSIONHPUPLOAD_H
#define N3_SDK_MESSAGE_MISSIONHPUPLOAD_H

#include <ros/service_traits.h>


#include <n3_sdk/MissionHpUploadRequest.h>
#include <n3_sdk/MissionHpUploadResponse.h>


namespace n3_sdk
{

struct MissionHpUpload
{

typedef MissionHpUploadRequest Request;
typedef MissionHpUploadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionHpUpload
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::MissionHpUpload > {
  static const char* value()
  {
    return "d057d61e861a72611b7918cfd8a98e4a";
  }

  static const char* value(const ::n3_sdk::MissionHpUpload&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::MissionHpUpload > {
  static const char* value()
  {
    return "n3_sdk/MissionHpUpload";
  }

  static const char* value(const ::n3_sdk::MissionHpUpload&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::MissionHpUploadRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionHpUpload > 
template<>
struct MD5Sum< ::n3_sdk::MissionHpUploadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionHpUpload >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpUploadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionHpUploadRequest> should match 
// service_traits::DataType< ::n3_sdk::MissionHpUpload > 
template<>
struct DataType< ::n3_sdk::MissionHpUploadRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionHpUpload >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpUploadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::MissionHpUploadResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionHpUpload > 
template<>
struct MD5Sum< ::n3_sdk::MissionHpUploadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionHpUpload >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpUploadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionHpUploadResponse> should match 
// service_traits::DataType< ::n3_sdk::MissionHpUpload > 
template<>
struct DataType< ::n3_sdk::MissionHpUploadResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionHpUpload >::value();
  }
  static const char* value(const ::n3_sdk::MissionHpUploadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_MISSIONHPUPLOAD_H
