// Generated by gencpp from file n3_sdk/MissionFmUpload.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MISSIONFMUPLOAD_H
#define N3_SDK_MESSAGE_MISSIONFMUPLOAD_H

#include <ros/service_traits.h>


#include <n3_sdk/MissionFmUploadRequest.h>
#include <n3_sdk/MissionFmUploadResponse.h>


namespace n3_sdk
{

struct MissionFmUpload
{

typedef MissionFmUploadRequest Request;
typedef MissionFmUploadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionFmUpload
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::MissionFmUpload > {
  static const char* value()
  {
    return "10ed872d3d019b452e558098ab5f5224";
  }

  static const char* value(const ::n3_sdk::MissionFmUpload&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::MissionFmUpload > {
  static const char* value()
  {
    return "n3_sdk/MissionFmUpload";
  }

  static const char* value(const ::n3_sdk::MissionFmUpload&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::MissionFmUploadRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionFmUpload > 
template<>
struct MD5Sum< ::n3_sdk::MissionFmUploadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionFmUpload >::value();
  }
  static const char* value(const ::n3_sdk::MissionFmUploadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionFmUploadRequest> should match 
// service_traits::DataType< ::n3_sdk::MissionFmUpload > 
template<>
struct DataType< ::n3_sdk::MissionFmUploadRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionFmUpload >::value();
  }
  static const char* value(const ::n3_sdk::MissionFmUploadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::MissionFmUploadResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionFmUpload > 
template<>
struct MD5Sum< ::n3_sdk::MissionFmUploadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionFmUpload >::value();
  }
  static const char* value(const ::n3_sdk::MissionFmUploadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionFmUploadResponse> should match 
// service_traits::DataType< ::n3_sdk::MissionFmUpload > 
template<>
struct DataType< ::n3_sdk::MissionFmUploadResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionFmUpload >::value();
  }
  static const char* value(const ::n3_sdk::MissionFmUploadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_MISSIONFMUPLOAD_H
