// Generated by gencpp from file n3_sdk/MissionCancel.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MISSIONCANCEL_H
#define N3_SDK_MESSAGE_MISSIONCANCEL_H

#include <ros/service_traits.h>


#include <n3_sdk/MissionCancelRequest.h>
#include <n3_sdk/MissionCancelResponse.h>


namespace n3_sdk
{

struct MissionCancel
{

typedef MissionCancelRequest Request;
typedef MissionCancelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionCancel
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::MissionCancel > {
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::n3_sdk::MissionCancel&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::MissionCancel > {
  static const char* value()
  {
    return "n3_sdk/MissionCancel";
  }

  static const char* value(const ::n3_sdk::MissionCancel&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::MissionCancelRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionCancel > 
template<>
struct MD5Sum< ::n3_sdk::MissionCancelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionCancel >::value();
  }
  static const char* value(const ::n3_sdk::MissionCancelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionCancelRequest> should match 
// service_traits::DataType< ::n3_sdk::MissionCancel > 
template<>
struct DataType< ::n3_sdk::MissionCancelRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionCancel >::value();
  }
  static const char* value(const ::n3_sdk::MissionCancelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::MissionCancelResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionCancel > 
template<>
struct MD5Sum< ::n3_sdk::MissionCancelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionCancel >::value();
  }
  static const char* value(const ::n3_sdk::MissionCancelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionCancelResponse> should match 
// service_traits::DataType< ::n3_sdk::MissionCancel > 
template<>
struct DataType< ::n3_sdk::MissionCancelResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionCancel >::value();
  }
  static const char* value(const ::n3_sdk::MissionCancelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_MISSIONCANCEL_H
