// Generated by gencpp from file n3_sdk/MissionWpUpload.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MISSIONWPUPLOAD_H
#define N3_SDK_MESSAGE_MISSIONWPUPLOAD_H

#include <ros/service_traits.h>


#include <n3_sdk/MissionWpUploadRequest.h>
#include <n3_sdk/MissionWpUploadResponse.h>


namespace n3_sdk
{

struct MissionWpUpload
{

typedef MissionWpUploadRequest Request;
typedef MissionWpUploadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionWpUpload
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::MissionWpUpload > {
  static const char* value()
  {
    return "ce0a38f3621e16d1b7a2d33b72384b5d";
  }

  static const char* value(const ::n3_sdk::MissionWpUpload&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::MissionWpUpload > {
  static const char* value()
  {
    return "n3_sdk/MissionWpUpload";
  }

  static const char* value(const ::n3_sdk::MissionWpUpload&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::MissionWpUploadRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionWpUpload > 
template<>
struct MD5Sum< ::n3_sdk::MissionWpUploadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionWpUpload >::value();
  }
  static const char* value(const ::n3_sdk::MissionWpUploadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionWpUploadRequest> should match 
// service_traits::DataType< ::n3_sdk::MissionWpUpload > 
template<>
struct DataType< ::n3_sdk::MissionWpUploadRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionWpUpload >::value();
  }
  static const char* value(const ::n3_sdk::MissionWpUploadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::MissionWpUploadResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionWpUpload > 
template<>
struct MD5Sum< ::n3_sdk::MissionWpUploadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionWpUpload >::value();
  }
  static const char* value(const ::n3_sdk::MissionWpUploadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionWpUploadResponse> should match 
// service_traits::DataType< ::n3_sdk::MissionWpUpload > 
template<>
struct DataType< ::n3_sdk::MissionWpUploadResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionWpUpload >::value();
  }
  static const char* value(const ::n3_sdk::MissionWpUploadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_MISSIONWPUPLOAD_H
