// Generated by gencpp from file n3_sdk/MissionStatusOther.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MISSIONSTATUSOTHER_H
#define N3_SDK_MESSAGE_MISSIONSTATUSOTHER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace n3_sdk
{
template <class ContainerAllocator>
struct MissionStatusOther_
{
  typedef MissionStatusOther_<ContainerAllocator> Type;

  MissionStatusOther_()
    : mission_type(0)
    , last_mission_type(0)
    , is_broken(0)
    , error_code(0)  {
    }
  MissionStatusOther_(const ContainerAllocator& _alloc)
    : mission_type(0)
    , last_mission_type(0)
    , is_broken(0)
    , error_code(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mission_type_type;
  _mission_type_type mission_type;

   typedef uint8_t _last_mission_type_type;
  _last_mission_type_type last_mission_type;

   typedef uint8_t _is_broken_type;
  _is_broken_type is_broken;

   typedef uint8_t _error_code_type;
  _error_code_type error_code;




  typedef boost::shared_ptr< ::n3_sdk::MissionStatusOther_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::n3_sdk::MissionStatusOther_<ContainerAllocator> const> ConstPtr;

}; // struct MissionStatusOther_

typedef ::n3_sdk::MissionStatusOther_<std::allocator<void> > MissionStatusOther;

typedef boost::shared_ptr< ::n3_sdk::MissionStatusOther > MissionStatusOtherPtr;
typedef boost::shared_ptr< ::n3_sdk::MissionStatusOther const> MissionStatusOtherConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::n3_sdk::MissionStatusOther_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::n3_sdk::MissionStatusOther_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace n3_sdk

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'n3_sdk': ['/home/ubuntu/fyp/catkin_ws/src/ugv/n3_sdk/msg', '/home/ubuntu/fyp/catkin_ws/devel/share/n3_sdk/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::n3_sdk::MissionStatusOther_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::n3_sdk::MissionStatusOther_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n3_sdk::MissionStatusOther_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n3_sdk::MissionStatusOther_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n3_sdk::MissionStatusOther_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n3_sdk::MissionStatusOther_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::n3_sdk::MissionStatusOther_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0261ae1eb980895a8685db930ec1a68";
  }

  static const char* value(const ::n3_sdk::MissionStatusOther_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0261ae1eb980895ULL;
  static const uint64_t static_value2 = 0xa8685db930ec1a68ULL;
};

template<class ContainerAllocator>
struct DataType< ::n3_sdk::MissionStatusOther_<ContainerAllocator> >
{
  static const char* value()
  {
    return "n3_sdk/MissionStatusOther";
  }

  static const char* value(const ::n3_sdk::MissionStatusOther_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::n3_sdk::MissionStatusOther_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mission_type\n\
uint8 last_mission_type\n\
uint8 is_broken\n\
uint8 error_code\n\
";
  }

  static const char* value(const ::n3_sdk::MissionStatusOther_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::n3_sdk::MissionStatusOther_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mission_type);
      stream.next(m.last_mission_type);
      stream.next(m.is_broken);
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionStatusOther_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::n3_sdk::MissionStatusOther_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::n3_sdk::MissionStatusOther_<ContainerAllocator>& v)
  {
    s << indent << "mission_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mission_type);
    s << indent << "last_mission_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.last_mission_type);
    s << indent << "is_broken: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_broken);
    s << indent << "error_code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // N3_SDK_MESSAGE_MISSIONSTATUSOTHER_H
