// Generated by gencpp from file n3_sdk/MissionStart.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MISSIONSTART_H
#define N3_SDK_MESSAGE_MISSIONSTART_H

#include <ros/service_traits.h>


#include <n3_sdk/MissionStartRequest.h>
#include <n3_sdk/MissionStartResponse.h>


namespace n3_sdk
{

struct MissionStart
{

typedef MissionStartRequest Request;
typedef MissionStartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionStart
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::MissionStart > {
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::n3_sdk::MissionStart&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::MissionStart > {
  static const char* value()
  {
    return "n3_sdk/MissionStart";
  }

  static const char* value(const ::n3_sdk::MissionStart&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::MissionStartRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionStart > 
template<>
struct MD5Sum< ::n3_sdk::MissionStartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionStart >::value();
  }
  static const char* value(const ::n3_sdk::MissionStartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionStartRequest> should match 
// service_traits::DataType< ::n3_sdk::MissionStart > 
template<>
struct DataType< ::n3_sdk::MissionStartRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionStart >::value();
  }
  static const char* value(const ::n3_sdk::MissionStartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::MissionStartResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::MissionStart > 
template<>
struct MD5Sum< ::n3_sdk::MissionStartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::MissionStart >::value();
  }
  static const char* value(const ::n3_sdk::MissionStartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::MissionStartResponse> should match 
// service_traits::DataType< ::n3_sdk::MissionStart > 
template<>
struct DataType< ::n3_sdk::MissionStartResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::MissionStart >::value();
  }
  static const char* value(const ::n3_sdk::MissionStartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_MISSIONSTART_H
