// Generated by gencpp from file n3_sdk/MissionPushInfo.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_MISSIONPUSHINFO_H
#define N3_SDK_MESSAGE_MISSIONPUSHINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace n3_sdk
{
template <class ContainerAllocator>
struct MissionPushInfo_
{
  typedef MissionPushInfo_<ContainerAllocator> Type;

  MissionPushInfo_()
    : type(0)
    , data_1(0)
    , data_2(0)
    , data_3(0)
    , data_4(0)
    , data_5(0)  {
    }
  MissionPushInfo_(const ContainerAllocator& _alloc)
    : type(0)
    , data_1(0)
    , data_2(0)
    , data_3(0)
    , data_4(0)
    , data_5(0)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;

   typedef uint8_t _data_1_type;
  _data_1_type data_1;

   typedef uint8_t _data_2_type;
  _data_2_type data_2;

   typedef uint8_t _data_3_type;
  _data_3_type data_3;

   typedef uint8_t _data_4_type;
  _data_4_type data_4;

   typedef uint8_t _data_5_type;
  _data_5_type data_5;




  typedef boost::shared_ptr< ::n3_sdk::MissionPushInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::n3_sdk::MissionPushInfo_<ContainerAllocator> const> ConstPtr;

}; // struct MissionPushInfo_

typedef ::n3_sdk::MissionPushInfo_<std::allocator<void> > MissionPushInfo;

typedef boost::shared_ptr< ::n3_sdk::MissionPushInfo > MissionPushInfoPtr;
typedef boost::shared_ptr< ::n3_sdk::MissionPushInfo const> MissionPushInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::n3_sdk::MissionPushInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::n3_sdk::MissionPushInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace n3_sdk

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'n3_sdk': ['/home/ubuntu/fyp/catkin_ws/src/ugv/n3_sdk/msg', '/home/ubuntu/fyp/catkin_ws/devel/share/n3_sdk/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::n3_sdk::MissionPushInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::n3_sdk::MissionPushInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n3_sdk::MissionPushInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n3_sdk::MissionPushInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n3_sdk::MissionPushInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n3_sdk::MissionPushInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::n3_sdk::MissionPushInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a520776ca6060b527ddc1be33a700532";
  }

  static const char* value(const ::n3_sdk::MissionPushInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa520776ca6060b52ULL;
  static const uint64_t static_value2 = 0x7ddc1be33a700532ULL;
};

template<class ContainerAllocator>
struct DataType< ::n3_sdk::MissionPushInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "n3_sdk/MissionPushInfo";
  }

  static const char* value(const ::n3_sdk::MissionPushInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::n3_sdk::MissionPushInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 type\n\
uint8 data_1\n\
uint8 data_2\n\
uint8 data_3\n\
uint8 data_4\n\
uint8 data_5\n\
";
  }

  static const char* value(const ::n3_sdk::MissionPushInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::n3_sdk::MissionPushInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.data_1);
      stream.next(m.data_2);
      stream.next(m.data_3);
      stream.next(m.data_4);
      stream.next(m.data_5);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionPushInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::n3_sdk::MissionPushInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::n3_sdk::MissionPushInfo_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "data_1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data_1);
    s << indent << "data_2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data_2);
    s << indent << "data_3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data_3);
    s << indent << "data_4: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data_4);
    s << indent << "data_5: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data_5);
  }
};

} // namespace message_operations
} // namespace ros

#endif // N3_SDK_MESSAGE_MISSIONPUSHINFO_H
