// Generated by gencpp from file n3_sdk/SyncFlagControl.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_SYNCFLAGCONTROL_H
#define N3_SDK_MESSAGE_SYNCFLAGCONTROL_H

#include <ros/service_traits.h>


#include <n3_sdk/SyncFlagControlRequest.h>
#include <n3_sdk/SyncFlagControlResponse.h>


namespace n3_sdk
{

struct SyncFlagControl
{

typedef SyncFlagControlRequest Request;
typedef SyncFlagControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SyncFlagControl
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::SyncFlagControl > {
  static const char* value()
  {
    return "848e0c067edd66153227f7c9aad5132b";
  }

  static const char* value(const ::n3_sdk::SyncFlagControl&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::SyncFlagControl > {
  static const char* value()
  {
    return "n3_sdk/SyncFlagControl";
  }

  static const char* value(const ::n3_sdk::SyncFlagControl&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::SyncFlagControlRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::SyncFlagControl > 
template<>
struct MD5Sum< ::n3_sdk::SyncFlagControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::SyncFlagControl >::value();
  }
  static const char* value(const ::n3_sdk::SyncFlagControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::SyncFlagControlRequest> should match 
// service_traits::DataType< ::n3_sdk::SyncFlagControl > 
template<>
struct DataType< ::n3_sdk::SyncFlagControlRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::SyncFlagControl >::value();
  }
  static const char* value(const ::n3_sdk::SyncFlagControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::SyncFlagControlResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::SyncFlagControl > 
template<>
struct MD5Sum< ::n3_sdk::SyncFlagControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::SyncFlagControl >::value();
  }
  static const char* value(const ::n3_sdk::SyncFlagControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::SyncFlagControlResponse> should match 
// service_traits::DataType< ::n3_sdk::SyncFlagControl > 
template<>
struct DataType< ::n3_sdk::SyncFlagControlResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::SyncFlagControl >::value();
  }
  static const char* value(const ::n3_sdk::SyncFlagControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_SYNCFLAGCONTROL_H
