// Generated by gencpp from file n3_sdk/VelocityControl.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_VELOCITYCONTROL_H
#define N3_SDK_MESSAGE_VELOCITYCONTROL_H

#include <ros/service_traits.h>


#include <n3_sdk/VelocityControlRequest.h>
#include <n3_sdk/VelocityControlResponse.h>


namespace n3_sdk
{

struct VelocityControl
{

typedef VelocityControlRequest Request;
typedef VelocityControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VelocityControl
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::VelocityControl > {
  static const char* value()
  {
    return "6984cb35c6197216fa18c628573ee383";
  }

  static const char* value(const ::n3_sdk::VelocityControl&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::VelocityControl > {
  static const char* value()
  {
    return "n3_sdk/VelocityControl";
  }

  static const char* value(const ::n3_sdk::VelocityControl&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::VelocityControlRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::VelocityControl > 
template<>
struct MD5Sum< ::n3_sdk::VelocityControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::VelocityControl >::value();
  }
  static const char* value(const ::n3_sdk::VelocityControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::VelocityControlRequest> should match 
// service_traits::DataType< ::n3_sdk::VelocityControl > 
template<>
struct DataType< ::n3_sdk::VelocityControlRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::VelocityControl >::value();
  }
  static const char* value(const ::n3_sdk::VelocityControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::VelocityControlResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::VelocityControl > 
template<>
struct MD5Sum< ::n3_sdk::VelocityControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::VelocityControl >::value();
  }
  static const char* value(const ::n3_sdk::VelocityControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::VelocityControlResponse> should match 
// service_traits::DataType< ::n3_sdk::VelocityControl > 
template<>
struct DataType< ::n3_sdk::VelocityControlResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::VelocityControl >::value();
  }
  static const char* value(const ::n3_sdk::VelocityControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_VELOCITYCONTROL_H
