// Generated by gencpp from file n3_sdk/VersionCheck.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_VERSIONCHECK_H
#define N3_SDK_MESSAGE_VERSIONCHECK_H

#include <ros/service_traits.h>


#include <n3_sdk/VersionCheckRequest.h>
#include <n3_sdk/VersionCheckResponse.h>


namespace n3_sdk
{

struct VersionCheck
{

typedef VersionCheckRequest Request;
typedef VersionCheckResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VersionCheck
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::VersionCheck > {
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::n3_sdk::VersionCheck&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::VersionCheck > {
  static const char* value()
  {
    return "n3_sdk/VersionCheck";
  }

  static const char* value(const ::n3_sdk::VersionCheck&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::VersionCheckRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::VersionCheck > 
template<>
struct MD5Sum< ::n3_sdk::VersionCheckRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::VersionCheck >::value();
  }
  static const char* value(const ::n3_sdk::VersionCheckRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::VersionCheckRequest> should match 
// service_traits::DataType< ::n3_sdk::VersionCheck > 
template<>
struct DataType< ::n3_sdk::VersionCheckRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::VersionCheck >::value();
  }
  static const char* value(const ::n3_sdk::VersionCheckRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::VersionCheckResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::VersionCheck > 
template<>
struct MD5Sum< ::n3_sdk::VersionCheckResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::VersionCheck >::value();
  }
  static const char* value(const ::n3_sdk::VersionCheckResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::VersionCheckResponse> should match 
// service_traits::DataType< ::n3_sdk::VersionCheck > 
template<>
struct DataType< ::n3_sdk::VersionCheckResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::VersionCheck >::value();
  }
  static const char* value(const ::n3_sdk::VersionCheckResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_VERSIONCHECK_H
