// Generated by gencpp from file n3_sdk/VirtualRCDataControlResponse.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_VIRTUALRCDATACONTROLRESPONSE_H
#define N3_SDK_MESSAGE_VIRTUALRCDATACONTROLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace n3_sdk
{
template <class ContainerAllocator>
struct VirtualRCDataControlResponse_
{
  typedef VirtualRCDataControlResponse_<ContainerAllocator> Type;

  VirtualRCDataControlResponse_()
    : result(false)  {
    }
  VirtualRCDataControlResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VirtualRCDataControlResponse_

typedef ::n3_sdk::VirtualRCDataControlResponse_<std::allocator<void> > VirtualRCDataControlResponse;

typedef boost::shared_ptr< ::n3_sdk::VirtualRCDataControlResponse > VirtualRCDataControlResponsePtr;
typedef boost::shared_ptr< ::n3_sdk::VirtualRCDataControlResponse const> VirtualRCDataControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace n3_sdk

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'n3_sdk': ['/home/ubuntu/fyp/catkin_ws/src/ugv/n3_sdk/msg', '/home/ubuntu/fyp/catkin_ws/devel/share/n3_sdk/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "n3_sdk/VirtualRCDataControlResponse";
  }

  static const char* value(const ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
\n\
";
  }

  static const char* value(const ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VirtualRCDataControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::n3_sdk::VirtualRCDataControlResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // N3_SDK_MESSAGE_VIRTUALRCDATACONTROLRESPONSE_H
