// Generated by gencpp from file n3_sdk/VirtualRCDataControl.msg
// DO NOT EDIT!


#ifndef N3_SDK_MESSAGE_VIRTUALRCDATACONTROL_H
#define N3_SDK_MESSAGE_VIRTUALRCDATACONTROL_H

#include <ros/service_traits.h>


#include <n3_sdk/VirtualRCDataControlRequest.h>
#include <n3_sdk/VirtualRCDataControlResponse.h>


namespace n3_sdk
{

struct VirtualRCDataControl
{

typedef VirtualRCDataControlRequest Request;
typedef VirtualRCDataControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VirtualRCDataControl
} // namespace n3_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::n3_sdk::VirtualRCDataControl > {
  static const char* value()
  {
    return "f79b1fb00a282f2e0e1596e014134c60";
  }

  static const char* value(const ::n3_sdk::VirtualRCDataControl&) { return value(); }
};

template<>
struct DataType< ::n3_sdk::VirtualRCDataControl > {
  static const char* value()
  {
    return "n3_sdk/VirtualRCDataControl";
  }

  static const char* value(const ::n3_sdk::VirtualRCDataControl&) { return value(); }
};


// service_traits::MD5Sum< ::n3_sdk::VirtualRCDataControlRequest> should match 
// service_traits::MD5Sum< ::n3_sdk::VirtualRCDataControl > 
template<>
struct MD5Sum< ::n3_sdk::VirtualRCDataControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::VirtualRCDataControl >::value();
  }
  static const char* value(const ::n3_sdk::VirtualRCDataControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::VirtualRCDataControlRequest> should match 
// service_traits::DataType< ::n3_sdk::VirtualRCDataControl > 
template<>
struct DataType< ::n3_sdk::VirtualRCDataControlRequest>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::VirtualRCDataControl >::value();
  }
  static const char* value(const ::n3_sdk::VirtualRCDataControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::n3_sdk::VirtualRCDataControlResponse> should match 
// service_traits::MD5Sum< ::n3_sdk::VirtualRCDataControl > 
template<>
struct MD5Sum< ::n3_sdk::VirtualRCDataControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::n3_sdk::VirtualRCDataControl >::value();
  }
  static const char* value(const ::n3_sdk::VirtualRCDataControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::n3_sdk::VirtualRCDataControlResponse> should match 
// service_traits::DataType< ::n3_sdk::VirtualRCDataControl > 
template<>
struct DataType< ::n3_sdk::VirtualRCDataControlResponse>
{
  static const char* value()
  {
    return DataType< ::n3_sdk::VirtualRCDataControl >::value();
  }
  static const char* value(const ::n3_sdk::VirtualRCDataControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // N3_SDK_MESSAGE_VIRTUALRCDATACONTROL_H
