; Auto-generated. Do not edit!


(cl:in-package dji_sdk_web_groundstation-msg)


;//! \htmlinclude WebWaypointReceiveResult.msg.html

(cl:defclass <WebWaypointReceiveResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass WebWaypointReceiveResult (<WebWaypointReceiveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <WebWaypointReceiveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'WebWaypointReceiveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name dji_sdk_web_groundstation-msg:<WebWaypointReceiveResult> is deprecated: use dji_sdk_web_groundstation-msg:WebWaypointReceiveResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <WebWaypointReceiveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader dji_sdk_web_groundstation-msg:result-val is deprecated.  Use dji_sdk_web_groundstation-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <WebWaypointReceiveResult>) ostream)
  "Serializes a message object of type '<WebWaypointReceiveResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'result) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <WebWaypointReceiveResult>) istream)
  "Deserializes a message object of type '<WebWaypointReceiveResult>"
    (cl:setf (cl:slot-value msg 'result) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<WebWaypointReceiveResult>)))
  "Returns string type for a message object of type '<WebWaypointReceiveResult>"
  "dji_sdk_web_groundstation/WebWaypointReceiveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'WebWaypointReceiveResult)))
  "Returns string type for a message object of type 'WebWaypointReceiveResult"
  "dji_sdk_web_groundstation/WebWaypointReceiveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<WebWaypointReceiveResult>)))
  "Returns md5sum for a message object of type '<WebWaypointReceiveResult>"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'WebWaypointReceiveResult)))
  "Returns md5sum for a message object of type 'WebWaypointReceiveResult"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<WebWaypointReceiveResult>)))
  "Returns full string definition for message of type '<WebWaypointReceiveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'WebWaypointReceiveResult)))
  "Returns full string definition for message of type 'WebWaypointReceiveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <WebWaypointReceiveResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <WebWaypointReceiveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'WebWaypointReceiveResult
    (cl:cons ':result (result msg))
))
