// Generated by gencpp from file dji_api/api_magnetic.msg
// DO NOT EDIT!


#ifndef DJI_API_MESSAGE_API_MAGNETIC_H
#define DJI_API_MESSAGE_API_MAGNETIC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dji_api
{
template <class ContainerAllocator>
struct api_magnetic_
{
  typedef api_magnetic_<ContainerAllocator> Type;

  api_magnetic_()
    : mx(0.0)
    , my(0.0)
    , mz(0.0)  {
    }
  api_magnetic_(const ContainerAllocator& _alloc)
    : mx(0.0)
    , my(0.0)
    , mz(0.0)  {
  (void)_alloc;
    }



   typedef float _mx_type;
  _mx_type mx;

   typedef float _my_type;
  _my_type my;

   typedef float _mz_type;
  _mz_type mz;




  typedef boost::shared_ptr< ::dji_api::api_magnetic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_api::api_magnetic_<ContainerAllocator> const> ConstPtr;

}; // struct api_magnetic_

typedef ::dji_api::api_magnetic_<std::allocator<void> > api_magnetic;

typedef boost::shared_ptr< ::dji_api::api_magnetic > api_magneticPtr;
typedef boost::shared_ptr< ::dji_api::api_magnetic const> api_magneticConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_api::api_magnetic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_api::api_magnetic_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dji_api

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'dji_api': ['/home/bobby/fyp/catkin_ws/src/dji_api/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dji_api::api_magnetic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_api::api_magnetic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_api::api_magnetic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_api::api_magnetic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_api::api_magnetic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_api::api_magnetic_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_api::api_magnetic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64ac045c4cbeb58b42caa30834be56a7";
  }

  static const char* value(const ::dji_api::api_magnetic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64ac045c4cbeb58bULL;
  static const uint64_t static_value2 = 0x42caa30834be56a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_api::api_magnetic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_api/api_magnetic";
  }

  static const char* value(const ::dji_api::api_magnetic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_api::api_magnetic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 mx\n\
float32 my\n\
float32 mz\n\
";
  }

  static const char* value(const ::dji_api::api_magnetic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_api::api_magnetic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mx);
      stream.next(m.my);
      stream.next(m.mz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct api_magnetic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_api::api_magnetic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_api::api_magnetic_<ContainerAllocator>& v)
  {
    s << indent << "mx: ";
    Printer<float>::stream(s, indent + "  ", v.mx);
    s << indent << "my: ";
    Printer<float>::stream(s, indent + "  ", v.my);
    s << indent << "mz: ";
    Printer<float>::stream(s, indent + "  ", v.mz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_API_MESSAGE_API_MAGNETIC_H
