// Generated by gencpp from file dji_api/api_velocity.msg
// DO NOT EDIT!


#ifndef DJI_API_MESSAGE_API_VELOCITY_H
#define DJI_API_MESSAGE_API_VELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dji_api
{
template <class ContainerAllocator>
struct api_velocity_
{
  typedef api_velocity_<ContainerAllocator> Type;

  api_velocity_()
    : vgx(0.0)
    , vgy(0.0)
    , vgz(0.0)  {
    }
  api_velocity_(const ContainerAllocator& _alloc)
    : vgx(0.0)
    , vgy(0.0)
    , vgz(0.0)  {
  (void)_alloc;
    }



   typedef float _vgx_type;
  _vgx_type vgx;

   typedef float _vgy_type;
  _vgy_type vgy;

   typedef float _vgz_type;
  _vgz_type vgz;




  typedef boost::shared_ptr< ::dji_api::api_velocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_api::api_velocity_<ContainerAllocator> const> ConstPtr;

}; // struct api_velocity_

typedef ::dji_api::api_velocity_<std::allocator<void> > api_velocity;

typedef boost::shared_ptr< ::dji_api::api_velocity > api_velocityPtr;
typedef boost::shared_ptr< ::dji_api::api_velocity const> api_velocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_api::api_velocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_api::api_velocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dji_api

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'dji_api': ['/home/bobby/fyp/catkin_ws/src/dji_api/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dji_api::api_velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_api::api_velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_api::api_velocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_api::api_velocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_api::api_velocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_api::api_velocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_api::api_velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf5f9e1e9a93c3b5ada672ea4e8faf92";
  }

  static const char* value(const ::dji_api::api_velocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf5f9e1e9a93c3b5ULL;
  static const uint64_t static_value2 = 0xada672ea4e8faf92ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_api::api_velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_api/api_velocity";
  }

  static const char* value(const ::dji_api::api_velocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_api::api_velocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vgx\n\
float32 vgy\n\
float32 vgz\n\
";
  }

  static const char* value(const ::dji_api::api_velocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_api::api_velocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vgx);
      stream.next(m.vgy);
      stream.next(m.vgz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct api_velocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_api::api_velocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_api::api_velocity_<ContainerAllocator>& v)
  {
    s << indent << "vgx: ";
    Printer<float>::stream(s, indent + "  ", v.vgx);
    s << indent << "vgy: ";
    Printer<float>::stream(s, indent + "  ", v.vgy);
    s << indent << "vgz: ";
    Printer<float>::stream(s, indent + "  ", v.vgz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_API_MESSAGE_API_VELOCITY_H
