// Generated by gencpp from file dji_api/api_rc.msg
// DO NOT EDIT!


#ifndef DJI_API_MESSAGE_API_RC_H
#define DJI_API_MESSAGE_API_RC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dji_api
{
template <class ContainerAllocator>
struct api_rc_
{
  typedef api_rc_<ContainerAllocator> Type;

  api_rc_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , throttle(0.0)
    , mode(0.0)
    , gear(0.0)  {
    }
  api_rc_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , throttle(0.0)
    , mode(0.0)
    , gear(0.0)  {
  (void)_alloc;
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _throttle_type;
  _throttle_type throttle;

   typedef float _mode_type;
  _mode_type mode;

   typedef float _gear_type;
  _gear_type gear;




  typedef boost::shared_ptr< ::dji_api::api_rc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_api::api_rc_<ContainerAllocator> const> ConstPtr;

}; // struct api_rc_

typedef ::dji_api::api_rc_<std::allocator<void> > api_rc;

typedef boost::shared_ptr< ::dji_api::api_rc > api_rcPtr;
typedef boost::shared_ptr< ::dji_api::api_rc const> api_rcConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_api::api_rc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_api::api_rc_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dji_api

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'dji_api': ['/home/bobby/fyp/catkin_ws/src/dji_api/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dji_api::api_rc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_api::api_rc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_api::api_rc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_api::api_rc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_api::api_rc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_api::api_rc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_api::api_rc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a789c8c64d1f9ced42fae82c795222dd";
  }

  static const char* value(const ::dji_api::api_rc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa789c8c64d1f9cedULL;
  static const uint64_t static_value2 = 0x42fae82c795222ddULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_api::api_rc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_api/api_rc";
  }

  static const char* value(const ::dji_api::api_rc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_api::api_rc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 roll\n\
float32 pitch\n\
float32 yaw\n\
float32 throttle\n\
float32 mode\n\
float32 gear\n\
";
  }

  static const char* value(const ::dji_api::api_rc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_api::api_rc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.throttle);
      stream.next(m.mode);
      stream.next(m.gear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct api_rc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_api::api_rc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_api::api_rc_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "throttle: ";
    Printer<float>::stream(s, indent + "  ", v.throttle);
    s << indent << "mode: ";
    Printer<float>::stream(s, indent + "  ", v.mode);
    s << indent << "gear: ";
    Printer<float>::stream(s, indent + "  ", v.gear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_API_MESSAGE_API_RC_H
